ims/urls.py
from django.urls import path

from . import views

# app_name = "polls"
# urlpatterns = [
#     # ex: /polls/
#     path("", views.index, name="index"),
#     # ex: /polls/5/
#     path("<int:question_id>/", views.detail, name="detail"),
#     # ex: /polls/5/results/
#     path("<int:question_id>/results/", views.results, name="results"),
#     # ex: /polls/5/vote/
#     path("<int:question_id>/vote/", views.vote, name="vote"),
# ]

app_name = "ims"
urlpatterns = [
    path("item/<str:uuid>/", views.DetailView.as_view(), name="detail"),
    path('ad/<int:id>/redirect/', views.ad_redirect_view, name='ad-redirect'),
    path("get-telegram-url/<str:uuid>/", views.get_telegram_url, name="get-telegram-url"),
    path("", views.index, name="index"),
    path("add/", views.add, name="add"),
    path("add_v2/", views.add_v2, name="add_v2"),  # 还未完成，已弃用，因为太繁琐了，还不如直接SSR前后端分离
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.urls import path, include, re_path
from django.http import HttpResponsePermanentRedirect

from ims.sitemaps import LinkSitemap

sitemaps = {
    'link': LinkSitemap,
}

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path('admin/', admin.site.urls),
    path("", include("ims.urls")),
    path("polls/", include("polls.urls")),
    path("unicorn/", include("django_unicorn.urls")),

    # 其他路径配置
    path('i18n/', include('django.conf.urls.i18n')),  # 如果不需要 i18n 功能，可以移除这一行
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
] 

# 添加静态文件的 URL
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 重定向旧版本带语言代码的URL，包括首页
urlpatterns += [
    path('en/', lambda request: HttpResponsePermanentRedirect("/")),
    path('zh-hans/', lambda request: HttpResponsePermanentRedirect("/")),
    path('en/<path:subpath>/', lambda request, subpath: HttpResponsePermanentRedirect(f"/{subpath}")),
    path('zh-hans/<path:subpath>/', lambda request, subpath: HttpResponsePermanentRedirect(f"/{subpath}")),
]

ims/models.py
import logging
import pprint
import re
import uuid

import requests
from bs4 import BeautifulSoup
from django.contrib import admin
from django.db import models, transaction
from django.urls import reverse
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from ims import tasks

# from django.utils.autoreload import logger


class LinkManager(models.Manager):
    def verified_and_invalid(self):
        return self.filter(verified_at__isnull=False, is_valid=False)

    def verified_and_valid(self):
        return self.filter(verified_at__isnull=False, is_valid=True)


class Search(models.Model):
    keyword = models.CharField(max_length=255, unique=True)
    search_count = models.IntegerField(default=0, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_search_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.keyword


class Ad(models.Model):

    PLACE_CHOICES = [
        (1, _('首页')),
        (2, _('详情页')),
    ]

    status = models.BooleanField(default=True, verbose_name=_("启用"))
    title = models.CharField(max_length=255, unique=True)
    # place = models.SmallIntegerField(choices=PLACE_CHOICES)
    place = models.ManyToManyField('AdPlace', verbose_name='展示位置')
    url = models.CharField(null=True, blank=True)
    image = models.ImageField(upload_to='', null=True, blank=True)
    click_count = models.IntegerField(default=0, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    start_at = models.DateTimeField()
    end_at = models.DateTimeField()

    def __str__(self):
        return self.title

class AdPlace(models.Model):
    code = models.SmallIntegerField(unique=True, db_index=True, verbose_name=_("位置代码"))
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

class Link(models.Model):
    UNKNOWN = 'unknown'
    GROUP = 'group'
    CHANNEL = 'channel'
    PERSONAL = 'personal'

    CATEGORY_CHOICES = [
        (UNKNOWN, _('未知')),
        (GROUP, _('群组')),
        (CHANNEL, _('频道')),
        (PERSONAL, _('个人')),
    ]

    category = models.CharField(max_length=10, choices=CATEGORY_CHOICES, default=UNKNOWN)
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    name = models.CharField(default="Updating...", max_length=128, verbose_name=_("Name"))
    description = models.TextField(max_length=512, verbose_name=_("Description"))
    member_count = models.IntegerField(default=0, verbose_name=_("用户数"))
    url = models.URLField(unique=True)  # Telegram链接
    
    # true则是用户提交的链接，false则是爬虫爬取的链接
    is_by_user = models.BooleanField(default=False, verbose_name=_("是否是用户提交的链接"))

    is_valid = models.BooleanField(default=False, verbose_name=_("有效的"))
    verified_at = models.DateTimeField(null=True, blank=True, verbose_name=_("验证时间"))

    #验证开始时间，不管是否验证成功
    verified_start_at = models.DateTimeField(null=True, blank=True, verbose_name=_("验证开始时间"))

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("创建时间"))
    updated_at = models.DateTimeField(auto_now=True)

    objects = LinkManager()

    def get_absolute_url(self):
        return reverse('ims:detail', args=[str(self.uuid)])

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        # 检查是否是新创建的对象
        if self.pk is None:
            url_changed = True
        else:
            # 获取当前数据库中的对象
            old_object = Link.objects.get(pk=self.pk)
            # 检查 'url' 字段是否改变
            url_changed = old_object.url != self.url

        # 调用父类的 save 方法保存对象
        super().save(*args, **kwargs)

        # 如果 'url' 发生了变化，则执行操作
        if url_changed:
            # tasks.verify_telegram.delay(self.id)
            # 确保在事务提交后执行任务
            transaction.on_commit(lambda: tasks.verify_telegram_dispatch(self.id))

    # def verified_telegram(self):
        # try:
        #     url = self.url
        #     headers = {
        #         'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'
        #     }
        #     response = requests.get(url, headers=headers)
        #
        #     if response.status_code == 200:
        #         html = response.text
        #         soup = BeautifulSoup(html, 'lxml')
        #
        #         # 提取 Telegram 名称和描述
        #         telegram_name = soup.select_one('.tgme_page_title span')
        #         self.name = telegram_name.text if telegram_name else 'none'
        #
        #         telegram_description = soup.select_one('.tgme_page_description')
        #         self.description = telegram_description.text if telegram_description else 'none'
        #
        #         telegram_member_count = soup.select_one('.tgme_page_extra')
        #         if telegram_member_count:
        #             match = re.search(r'(\d[\d\s,]*)members', telegram_member_count.text)
        #             if match:
        #                 self.member_count = int(re.sub(r'\D', '', match.group(1)))
        #                 self.category = self.GROUP
        #             match = re.search(r'(\d[\d\s,]*)subscribers', telegram_member_count.text)
        #             if match:
        #                 self.member_count = int(re.sub(r'\D', '', match.group(1)))
        #                 self.category = self.CHANNEL
        #             match = re.search(r'^@\w+$', telegram_member_count.text)
        #             if match:
        #                 self.category = self.PERSONAL
        #
        #         # 检查是否有效
        #         self.is_valid = True
        #         robots_meta = soup.find('meta', attrs={'name': 'robots'})
        #         if robots_meta and robots_meta.get('content') != 'none':
        #             self.is_valid = False
        #
        #         self.verified_at = now()
        #         self.save()
        #
        #     else:
        #         # 记录错误日志
        #         logger.error("HTTP 请求失败" + pprint.pformat({
        #             'URL': url,
        #             'status': response.status_code,
        #             'headers': response.headers,
        #             'body': response.text,
        #         }, indent=4))
        #
        # except Exception as e:
        #     logger.error(f"发生异常: {e}")

ims/forms.py
from django import forms
# from django_recaptcha.fields import ReCaptchaField

from .models import Link


class AddForm(forms.ModelForm):
    url = forms.CharField(widget=forms.Textarea, help_text="输入多个URL，每行一个。")

    class Meta:
        model = Link
        fields = ['url']


class MultiURLForm(forms.Form):
    # captcha = ReCaptchaField()
    urls = forms.CharField(widget=forms.Textarea, help_text="输入多个URL，每行一个。")
    # urls = forms.CharField(
    #     widget=forms.Textarea(attrs={
    #         'class': 'relative w-full p-4 placeholder-transparent transition-all border rounded outline-none focus-visible:outline-none peer border-slate-200 text-slate-500 autofill:bg-white invalid:border-pink-500 invalid:text-pink-500 focus:border-stone-500 focus:outline-none invalid:focus:border-pink-500 disabled:cursor-not-allowed disabled:bg-slate-50 disabled:text-slate-400',
    #         'placeholder': 'Write your message'
    #     }),
    #     help_text="输入多个URL，每行一个。"
    # )

ims/views.py
from datetime import timedelta
import re
from collections import Counter

import jieba
import requests
from constance import config
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.core.validators import URLValidator
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.db.models import F


from common.utils import extract_keywords
from ims import tasks
from .forms import AddForm, MultiURLForm
from .models import Ad, Link

def ad_redirect_view(request, id):
    # 获取广告对象
    ad = get_object_or_404(Ad, id=id)

    # 自增 click_count
    ad.click_count = F('click_count') + 1
    ad.save(update_fields=['click_count'])

    # 跳转到广告的 URL
    return redirect(ad.url)

def index(request):
    return render(request, "ims/index.html")


def add(request):
    return render(request, "ims/add.html")


def add_v22(request):
    saved_object = None
    if request.method == 'POST':
        form = AddForm(request.POST)
        if form.is_valid():
            # 处理表单数据
            saved_object = form.save()
            messages.success(request, '表单提交成功！')
    else:
        form = AddForm()

    return render(request, 'ims/add_v2.html', {'form': form, 'saved_object': saved_object})


def add_v2(request):
    form = MultiURLForm(request.POST or None)
    saved_links = []  # 用于存储成功保存的Link实例
    if request.method == 'POST' and form.is_valid():
        urls_field = form.cleaned_data['urls']
        urls = urls_field.splitlines()
        for url in urls:
            url = url.strip()
            if url:
                validate = URLValidator()
                try:
                    validate(url)
                    link = Link.objects.create(url=url)
                    saved_links.append(link)  # 添加到列表中
                except ValidationError:
                    messages.error(request, f"'{url}' 不是一个有效的URL。")
                    return redirect('ims:add_v2')
        if saved_links:
            messages.success(request, '所有有效URL已添加！')
            return redirect('ims:add_v2')
        # form = MultiURLForm()  # 重置表单

    return render(request, 'ims/add_v2.html', {'form': form, 'saved_links': saved_links})


class DetailView(generic.DetailView):
    model = Link
    template_name = "ims/detail.html"

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Link.objects.filter(pub_date__lte=timezone.now())

    def get_object(self):
        uuid = self.kwargs.get('uuid')
        link = get_object_or_404(Link, uuid=uuid)

        # 如果更新时间是一小时前，则派遣更新
        if link.verified_start_at <= timezone.now() - timedelta(hours=1):
            tasks.verify_telegram_dispatch(link.id)
            
        return link

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        link = self.get_object()

        context['title'] = link.name

        text = link.name + link.description
        keywords = extract_keywords(text)
        context['keywords'] = ','.join(keywords)

        context['description'] = link.description
        return context


# Recaptcha v3：
@csrf_exempt
def get_telegram_url(request, uuid):
    recaptcha_response = request.POST.get('recaptcha_response')
    data = {
        'secret': config.RECAPTCHA_PRIVATE_KEY,
        'response': recaptcha_response
    }
    r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
    result = r.json()
    score = result.get('score', 0)

    # 更改验证Recaptcha响应的方式
    if result['success'] and result['action'] == 'submit' and score >= 0.1: # （0.0 到 1.0），分数越高，可能是人类的概率越大
        link = get_object_or_404(Link, uuid=uuid)
        return JsonResponse({'success': True, 'score': score, 'telegram_url': link.url})
    else:
        return JsonResponse({'success': False, 'score': score})

# # Recaptcha v2：
# @csrf_exempt
# def get_telegram_url(request, uuid):
#     recaptcha_response = request.POST.get('recaptcha_response')
#     data = {
#         'secret': config.RECAPTCHA_PRIVATE_KEY,
#         # 'secret': '6LcQzUApAAAAANs-5hxBDzXEynxcH6LDD_UuwjjS',
#         'response': recaptcha_response
#     }
#     r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
#     result = r.json()

#     if result['success']:
#         link = get_object_or_404(Link, uuid=uuid)
#         return JsonResponse({'success': True, 'telegram_url': link.url})
#     else:
#         return JsonResponse({'success': False})

ims/templates/unicorn/detail.html
{% load custom_filter %}
<div class="max-w-2xl mx-auto mt-10">

    <div class="text-center">
        <h1 class="text-center text-3xl">
            {{ link.name|default:"数据正在更新中" }}
        </h1>
        <div class="text-gray-500 my-3">
            用户数：{{ link.member_count|format_number }}
        </div>
        <div class="text-gray-500">
            {{ link.description|default:"数据正在更新中" }}
        </div>


        <!-- Recaptcha v3： -->
        <script src='https://www.recaptcha.net/recaptcha/api.js?render={{ config.RECAPTCHA_PUBLIC_KEY }}'></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

        <script>
            function submitRecaptcha() {
                grecaptcha.ready(function() {
                    grecaptcha.execute('{{ config.RECAPTCHA_PUBLIC_KEY }}', {action: 'submit'}).then(function(token) {
                        // 发送 AJAX 请求到后端
                        $.post("{% url 'ims:get-telegram-url' link.uuid %}", {
                            recaptcha_response: token
                        }, function (data) {
                            if (data.success) {
                                window.location.href = data.telegram_url;
                            } else {
                                $("#message").html("得分: "+data.score+", 人机验证失败, 请更换浏览器或稍后重试");
                            }
                        });
                    });
                });
            }
        </script>

        <!-- Component: Base primary basic button -->
        <div id="message" class="text-red-500"></div>
        <button rel="nofollow" onclick="submitRecaptcha()"
                class="mt-3 inline-flex items-center justify-center h-10 gap-2 px-5 text-sm font-medium tracking-wide text-white transition duration-300 rounded-full focus-visible:outline-none whitespace-nowrap bg-sky-500 hover:bg-sky-600 focus:bg-sky-700 disabled:cursor-not-allowed disabled:border-sky-300 disabled:bg-sky-300 disabled:shadow-none">
            {#        <a target="_blank" rel="nofollow" href="{{ link.url }}" class="mt-8 inline-flex items-center justify-center h-10 gap-2 px-5 text-sm font-medium tracking-wide text-white transition duration-300 rounded-full focus-visible:outline-none whitespace-nowrap bg-sky-500 hover:bg-sky-600 focus:bg-sky-700 disabled:cursor-not-allowed disabled:border-sky-300 disabled:bg-sky-300 disabled:shadow-none">#}
            <span>前往 Telegram</span>
        </button>

        <!-- Recaptcha v2： -->
        <!-- <div class="g-recaptcha inline-block mx-auto mt-8" data-sitekey="{{ config.RECAPTCHA_PUBLIC_KEY }}"
             data-callback="setRecaptchaResponse"></div>
        <script src='https://www.recaptcha.net/recaptcha/api.js' async defer></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script>
            function setRecaptchaResponse(response) {
                $("#message").html("");
            }

            function submitRecaptcha() {
                let recaptchaResponse = grecaptcha.getResponse();

                // 发送 AJAX 请求到后端
                $.post("{% url 'ims:get-telegram-url' link.uuid %}", {
                    recaptcha_response: recaptchaResponse
                }, function (data) {
                    if (data.success) {
                        window.location.href = data.telegram_url;
                    } else {
                        $("#message").html("请先点击人机验证！");
                    }
                });
            }
        </script> -->
        <!-- Component: Base primary basic button -->
        <!-- <div id="message" class="text-red-500"></div>
        <button rel="nofollow" onclick="submitRecaptcha()"
                class="mt-3 inline-flex items-center justify-center h-10 gap-2 px-5 text-sm font-medium tracking-wide text-white transition duration-300 rounded-full focus-visible:outline-none whitespace-nowrap bg-sky-500 hover:bg-sky-600 focus:bg-sky-700 disabled:cursor-not-allowed disabled:border-sky-300 disabled:bg-sky-300 disabled:shadow-none">
            {#        <a target="_blank" rel="nofollow" href="{{ link.url }}" class="mt-8 inline-flex items-center justify-center h-10 gap-2 px-5 text-sm font-medium tracking-wide text-white transition duration-300 rounded-full focus-visible:outline-none whitespace-nowrap bg-sky-500 hover:bg-sky-600 focus:bg-sky-700 disabled:cursor-not-allowed disabled:border-sky-300 disabled:bg-sky-300 disabled:shadow-none">#}
            <span>前往 Telegram</span>
        </button> -->

        <!-- End Base primary basic button -->
        <div class="text-gray-500 mt-5 text-sm">
            更新时间：{{ link.verified_at }}
        </div>

        {% if ads %}
            {% for ad in ads %}
                <div class="mt-5">
                    <span class="text-gray-500">AD:</span>
                    <a href="{% url 'ims:ad-redirect' id=ad.id %}"
                    class="border-b border-dashed border-gray-600 hover:border-gray-400 text-orange-500">
                        {{ ad.title }}
                    </a>  
                </div>
            {% endfor %}
        {% endif %}

    </div>

    {% if hot_links %}
        <div class="text-gray-500 mt-8 px-4">其它热门 Telegram：</div>
        <ul class="max-w-3xl mx-auto">
            {% for link in hot_links %}
                <li class="border py-3 px-4 m-2 shadow space-y-1">
                    <a href="{% url 'ims:detail' link.uuid %}"
                       class="border-b border-dashed border-gray-600 hover:border-gray-400 text-cyan-500">
                        {{ link.name|truncatechars:50|default:"数据正在更新中" }}
                    </a>
                    <div class="text-gray-500 text-sm">
                        {{ link.description|truncatechars:90 }}
                    </div>
                    <div class="text-gray-500 text-xs">
                        <span class="inline-block border rounded px-2">
                            用户数：{{ link.member_count|format_number }}
                        </span>
                        <span class="inline-block border rounded px-2">
                            类型：{{ link.get_category_display }}
                        </span>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% endif %}

    {% if random_links %}
        <div class="text-gray-500 mt-8 px-4">随机推荐 Telegram：</div>
        <ul class="max-w-3xl mx-auto">
            {% for link in random_links %}
                <li class="border py-3 px-4 m-2 shadow space-y-1">
                    <a href="{% url 'ims:detail' link.uuid %}"
                       class="border-b border-dashed border-gray-600 hover:border-gray-400 text-cyan-500">
                        {{ link.name|truncatechars:50|default:"数据正在更新中" }}
                    </a>
                    <div class="text-gray-500 text-sm">
                        {{ link.description|truncatechars:90 }}
                    </div>
                    <div class="text-gray-500 text-xs">
                        <span class="inline-block border rounded px-2">
                            用户数：{{ link.member_count|format_number }}
                        </span>
                        <span class="inline-block border rounded px-2">
                            类型：{{ link.get_category_display }}
                        </span>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% endif %}

</div>

ims/templates/unicorn/hello-magic.html
<div>
    <!-- put component code here -->
</div>

ims/templates/unicorn/hello-world.html
<div>
  <input unicorn:model="name" type="text" id="text" /><br />
  Hello {{ name|title }}
    <div unicorn:loading>Updating!</div>
</div>

ims/templates/unicorn/index.html
{% load i18n %}
{% load custom_filter %}
<div>

    <div class="bg-purple-400 shadow-md mb-5 py-10 px-5">

        <div class="flex justify-center max-w-3xl mx-auto mb-5 text-white">
            {% blocktrans %}请输入您要搜索的: 频道/群组/机器人/个人号{% endblocktrans %}
        </div>
        <form action="/">
            <div class="relative flex justify-center max-w-3xl mx-auto">
                <input type="search" name="q" placeholder="搜索..." value="{{ query }}"
                       class="pl-3 pr-20 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent w-full"/>
                <button class="absolute inset-y-0 right-0 px-4 text-white bg-blue-500 rounded-r-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-opacity-50">
                    搜索
                </button>
            </div>
        </form>
        {% if top_searches %}
            <div class="max-w-3xl mx-auto mt-5 text-white space-y-2 space-x-1">
                热门关键词：
                {% for search in top_searches %}
                    <a href="{% url 'ims:index' %}?q={{ search.keyword|urlencode }}" class="inline-flex items-center justify-center h-8 gap-2 px-4 text-xs font-medium tracking-wide transition duration-300 rounded-full focus-visible:outline-none justify-self-center whitespace-nowrap bg-fuchsia-200 text-fuchsia-500 hover:bg-fuchsia-300 hover:text-fuchsia-600 focus:bg-fuchsia-400 focus:text-fuchsia-700 disabled:cursor-not-allowed disabled:border-fuchsia-300 disabled:bg-fuchsia-300 disabled:text-fuchsia-400 disabled:shadow-none">
                        <span>{{ search.keyword }}</span>
                    </a>
                {% endfor %}
            </div>
        {% endif %}

    </div>

    {% if ads %}
        {% for ad in ads %}
            <div class="my-5 text-center">
                <span class="text-gray-500">AD:</span>
                <a href="{% url 'ims:ad-redirect' id=ad.id %}"
                class="border-b border-dashed border-gray-600 hover:border-gray-400 text-orange-500">
                    {{ ad.title }}
                </a>  
            </div>
        {% endfor %}
    {% endif %}

    {% if links %}
        <ul class="max-w-3xl mx-auto">
            {% for link in links %}
                <li class="border py-3 px-4 m-2 shadow space-y-1">
                    <a href="{% url 'ims:detail' link.uuid %}"
                       class="border-b border-dashed border-gray-600 hover:border-gray-400 text-cyan-500">
                        {{ link.name|truncatechars:50|default:"数据正在更新中" }}
                    </a>
                    <div class="text-gray-500 text-sm">
                        {{ link.description|truncatechars:90 }}
                    </div>
                    <div class="text-gray-500 text-xs">
                        <span class="inline-block border rounded px-2">
                            用户数：{{ link.member_count|format_number }}
                        </span>
                        <span class="inline-block border rounded px-2">
                            类型：{{ link.get_category_display }}
                        </span>
                    </div>
                </li>
            {% endfor %}
        </ul>

        <div class="flex justify-center items-center m-5">
            <!-- Component: Small outline button with animation  -->
            <button unicorn:click="load_more" unicorn:key="load_more"
                    class="group inline-flex items-center justify-center h-8 gap-2 px-4 text-xs font-medium tracking-wide transition duration-300 border rounded focus-visible:outline-none whitespace-nowrap border-orange-500 text-orange-500 hover:border-orange-600 hover:text-orange-600 focus:border-orange-700 focus:text-orange-700 disabled:cursor-not-allowed disabled:border-orange-300 disabled:text-orange-300 disabled:shadow-none">
                <span>
                    {% if all_articles_loaded %}
                        {% trans "已加载全部" %}
                    {% else %}
                        {% trans "加载更多" %}
                    {% endif %}
                </span>
                <span class="relative only:-mx-6" unicorn:loading unicorn:target="load_more">
                    <svg class="w-4 h-4 animate-spin text-orange-500 group-hover:text-orange-600 group-focus:text-orange-700"
                         xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" role="graphics-symbol"
                         aria-labelledby="title-76 desc-76">
                    <title id="title-76">Icon title</title>
                    <desc id="desc-76">
                    A more detailed description of the icon
                    </desc>
                    <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                    <path class="opacity-75" fill="currentColor"
                          d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                </span>
            </button>
            <!-- End Small outline button with animation  -->
        </div>
    {% else %}
        <p class="text-center text-gray-500 text-xl">没有相关记录</p>
    {% endif %}

</div>