ims/urls.py
from django.urls import path

from . import views

# app_name = "polls"
# urlpatterns = [
#     # ex: /polls/
#     path("", views.index, name="index"),
#     # ex: /polls/5/
#     path("<int:question_id>/", views.detail, name="detail"),
#     # ex: /polls/5/results/
#     path("<int:question_id>/results/", views.results, name="results"),
#     # ex: /polls/5/vote/
#     path("<int:question_id>/vote/", views.vote, name="vote"),
# ]

app_name = "ims"
urlpatterns = [
    path("item/<str:uuid>/", views.DetailView.as_view(), name="detail"),
    path('ad/<int:id>/redirect/', views.ad_redirect_view, name='ad-redirect'),
    path("get-telegram-url/<str:uuid>/", views.get_telegram_url, name="get-telegram-url"),
    path("", views.index, name="index"),
    path("add/", views.add, name="add"),
    path("add_v2/", views.add_v2, name="add_v2"),  # 还未完成，已弃用，因为太繁琐了，还不如直接SSR前后端分离
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.urls import path, include, re_path
from django.http import HttpResponsePermanentRedirect

from ims.sitemaps import LinkSitemap

sitemaps = {
    'link': LinkSitemap,
}

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path('admin/', admin.site.urls),
    path("", include("ims.urls")),
    path("polls/", include("polls.urls")),
    path("unicorn/", include("django_unicorn.urls")),

    # 其他路径配置
    path('i18n/', include('django.conf.urls.i18n')),  # 如果不需要 i18n 功能，可以移除这一行
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
] 

# 添加静态文件的 URL
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 重定向旧版本带语言代码的URL，包括首页
urlpatterns += [
    path('en/', lambda request: HttpResponsePermanentRedirect("/")),
    path('zh-hans/', lambda request: HttpResponsePermanentRedirect("/")),
    path('en/<path:subpath>/', lambda request, subpath: HttpResponsePermanentRedirect(f"/{subpath}")),
    path('zh-hans/<path:subpath>/', lambda request, subpath: HttpResponsePermanentRedirect(f"/{subpath}")),
]

templates/layout/_language.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% load lang_switch %}

{% if false %} <!-- 取消多语言 -->
<div class="flex justify-center items-center">
    <!-- Component: Basic dropdown menu -->
    <div class="relative inline-flex" x-data="{ open: false, selectedLanguage: '' }"
         x-init="$watch('selectedLanguage', value => { if (value) setTimeout(() => { $refs.languageForm.submit() }, 1) })"
    >
        <!--  Start Dropdown trigger -->
        <button @click="open = ! open" @click.away="open = false"
                class="inline-flex items-center justify-center h-10 gap-1 px-5 text-sm font-medium tracking-wide transition duration-300 rounded focus-visible:outline-none justify-self-center whitespace-nowrap text-purple-500 hover:bg-emerald-50 hover:text-emerald-600 focus:bg-emerald-100 focus:text-emerald-700 disabled:cursor-not-allowed disabled:text-emerald-300 disabled:shadow-none disabled:hover:bg-transparent">
            <span>{{ current_language_info.name_local }} ({{ current_language_info.name }})</span>
            <span class="relative only:-mx-5">
      <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"
           stroke-width="1.5" aria-labelledby="t-01 d-01" role="graphics-symbol">
        <title id="t-01">Button icon</title>
        <desc id="d-01">An icon describing the buttons usage</desc>
        <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5"></path>
      </svg>
    </span>
        </button>
        <!--  End Dropdown trigger -->
        <!-- Start Menu list -->
        <ul x-show="open" x-cloak
            class="absolute z-20 flex flex-col py-2 mt-1 list-none bg-white rounded shadow-md border w-72 bottom-full shadow-slate-500/10">
                {% for lang in languages %}
                    <li>

                        <form action="{% url 'set_language' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="language" value="{{ lang.code }}">
                            <div onclick="this.closest('form').submit()"
                                class="flex items-start justify-start gap-2 p-2 px-5 transition-colors duration-300
                            {% if lang.code == LANGUAGE_CODE %}
                                text-emerald-500
                            {% else %}
                                text-slate-500
                            {% endif %}
                            hover:bg-emerald-50 hover:text-emerald-500 focus:bg-emerald-50 focus:text-emerald-600 focus:outline-none focus-visible:outline-none cursor-pointer">
                                <span class="flex flex-col gap-1 overflow-hidden whitespace-nowrap">
                                    <span class="leading-5 truncate">{{ lang.local_name }} ({{ lang.name }})</span>
                                </span>
                            </div>
                        </form>

                    </li>
                {% endfor %}
        </ul>
        <!-- End Menu list -->

        <!-- Hidden Form for Language Change -->
        <form x-ref="languageForm" action="{% url 'set_language' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="language" :value="selectedLanguage">
        </form>
    </div>
    <!-- End Basic dropdown menu-->
</div>
{% endif %}

templates/layout/base.html
{% load i18n %}
{% load static %}
{% load custom_tags %}
<!DOCTYPE html>
<html lang="{% get_lang_code %}">
<head>

    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-57X24HHD');</script>
    <!-- End Google Tag Manager -->

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>{% if title %}{{ title }} - {% endif %}Telegram 导航索引大全</title>
    {% if keywords %}
        <meta name="keywords" content="{{ keywords }}" />
    {% else %}
        <meta name="keywords" content="Telegram中文搜,电报中文搜索,电报中文工具,小飞机vpn,电报索引工具,telegram索引机器人,telegram搜索工具,电报,中文,telegram群组,电报群,电报群组,电报群组大全,电报群组导航,tnav" />
    {% endif %}
    {% if description %}
        <meta name="description" content="{{ description }}" />
    {% else %}
        <meta name="description" content="Tnav(tnav.me) 是一个 Telegram 群组分享平台，为 Telegram 用户提供各种 Telegram 群组/频道/机器人 等导航索引服务。" />
    {% endif %}

    <style>
        [x-cloak] {
            display: none !important;
        }
    </style>

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">

    <link rel="stylesheet" href="{% static "css/output.css" %}?11">
    <link rel="stylesheet" href="{% static "css/messages.css" %}">
    <script src="https://cdn.jsdelivr.net/npm/alpinejs@2.8.0/dist/alpine.js" defer></script>

    {% block extra_scripts %}{% endblock %}
</head>
<body>

    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-57X24HHD"
        height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->

<header class="bg-purple-500 shadow py-4">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex justify-between items-center">
        <!-- Logo -->
        <a class="flex-shrink-0 rounded-xl border-2 overflow-hidden" href="/">
            <img class="h-8 w-8" src="/static/logo/img.png" alt="Logo">
        </a>

        <!-- 网站名称，链接到首页 -->
        <a href="/" class="text-white hover:text-gray-300">
            Telegram 导航索引大全
        </a>

        <a href="{% url 'ims:add' %}" class="text-white hover:text-gray-300 flex items-center rounded border pl-1 pr-2 py-1">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                 stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v12m6-6H6"></path>
            </svg>
            {% trans "Add" %}
        </a>
    </div>
</header>

<main>
    {% block content %}
        <!-- 主要内容区域 -->
    {% endblock %}
</main>

<footer class="my-3">
    <!-- 交流群 -->
    <div class="bg-gray-100 py-4">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="text-center text-gray-500">
                官方交流群： <a href="https://t.me/tnav_me" class="text-blue-500 hover:text-blue-700">https://t.me/tnav_me</a>
            </div>
        </div>
    </div>

    {% include 'layout/_language.html' %}
</footer>
</body>
</html>